name: Update README with JSON
on:
  schedule:
    - cron: '0 0 * * 1' # Runs at 00:00, only on Monday
  workflow_dispatch:      # Permite ejecutarlo manualmente

permissions:
  contents: write  # Esto le da permiso explícito al bot para escribir y hacer push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch JSON and Update README
        run: |
          # 1. Descargar el JSON de npoint
          JSON_DATA=$(curl -s https://api.npoint.io/03144058aa3a6263fb8c)
          
          # 2. Formatear el JSON para que se vea bonito (opcional, requiere jq)
          # Si no quieres formatearlo, usa solo JSON_DATA
          
          # 3. Insertar el JSON entre las marcas del README
          perl -i -0777 -pe "s/().*()/\${1}\n\`\`\`json\n${JSON_DATA}\n\`\`\`\n\${2}/s" README.md

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add README.md
          
          # Solo procedemos si hay cambios reales
          if ! git diff --cached --exit-code; then
            git commit -m "Update JSON in README"
            # El rebase soluciona el error de "remote contains work that you do not have locally"
            git pull --rebase origin main
            git push origin main
          else
            echo "No hay cambios para subir."
          fi
