name: Update README with JSON
on:
  schedule:
    - cron: '*/30 * * * *' # Se ejecuta cada 30 min
  workflow_dispatch:      # Permite ejecutarlo manualmente

permissions:
  contents: write  # Esto le da permiso explícito al bot para escribir y hacer push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch JSON and Update README
        run: |
          # 1. Descargar el JSON de npoint
          JSON_DATA=$(curl -s https://api.npoint.io/03144058aa3a6263fb8c)
          
          # 2. Formatear el JSON para que se vea bonito (opcional, requiere jq)
          # Si no quieres formatearlo, usa solo JSON_DATA
          
          # 3. Insertar el JSON entre las marcas del README
          perl -i -0777 -pe "s/().*()/\${1}\n\`\`\`json\n${JSON_DATA}\n\`\`\`\n\${2}/s" README.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          # Solo hace commit si hay cambios detectados
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update JSON in README" && git push)
